# Build settings

# Halt processing when a warning is raised when building the docs.
# https://www.mkdocs.org/user-guide/configuration/#strict
strict: true

# Set the remote branch to commit to when using `gh-deploy` to deploy to GitHub Pages.
# https://www.mkdocs.org/user-guide/configuration/#remote_branch
remote_branch: gh-pages

# Hooks
# https://www.mkdocs.org/user-guide/configuration/#hooks

hooks:
  - mkdocs-hooks/custom-edit-url.py

# General site info

# Metadata

# Set the main title for the project.
# Required setting.
# https://www.mkdocs.org/user-guide/configuration/#site_name
site_name: Renovate Docs

# Set the canonical URL of the site.
# https://www.mkdocs.org/user-guide/configuration/#site_url
site_url: 'https://docs.renovatebot.com'

# Set the site description, this will add a meta tag to the generated HTML header.
# https://www.mkdocs.org/user-guide/configuration/#site_description
site_description: 'Renovate documentation.'

# Upstream Git repository information
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_name: renovatebot/renovate
repo_url: https://github.com/renovatebot/renovate
edit_uri: edit/main/docs/usage/

# Theme settings
theme:
  name: 'material'

  # Allow overriding the Material for MkDocs themes with a 'overrides' directory.
  # The custom_dir points to the overrides folder, this folder has the code for our announcement bar.
  # The easiest way to disable the announcement bar is to comment out the custom_dir: overrides entry in this mkdocs.yml file.
  # https://squidfunk.github.io/mkdocs-material/customization/#setup-and-theme-structure
  custom_dir: overrides

  logo: 'assets/images/logo.png'
  favicon: 'assets/images/logo.png'

  icon:
    repo: fontawesome/brands/github # Custom icon for link to GitHub repository in header

  # Setup colorscheme for Light and Dark mode
  # Setup icon set for the light/dark mode toggle
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/

  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: 'indigo'
      accent: 'indigo'
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: 'teal'
      accent: 'teal'

  features:
    # Back to top button
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=back+to+top#back-to-top-button
    - navigation.top

    # Integrate table of contents into left sidebar
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=integrate#integrated-table-of-contents
    - toc.integrate

    # Automatically scroll the navigation sidebar, so the active anchor is always on screen.
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-following
    - toc.follow

    # Use instant loading for internal links
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=instant#instant-loading
    - navigation.instant

    # Mark the announcement bar as read.
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#mark-as-read
    - announce.dismiss

# CSS and JavaScript customizations

extra_css:
  - 'assets/css/style.css'

extra_javascript:
  - 'assets/js/fx.js'

# Extensions
markdown_extensions:
  # Adds the ability to attach arbitrary key-value pairs to a document
  # via front matter written in YAML syntax before the Markdown.
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/?h=meta#metadata
  - meta

  # The toc.permalink extension adds a permalink behind each heading.
  # https://python-markdown.github.io/extensions/toc/#usage
  - toc:
      permalink: true

  # The Highlight extension adds support for syntax highlighting of code blocks (with the help of SuperFences)
  # and inline code blocks (with the help of InlineHilite).
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/?h=highlig#highlight
  - pymdownx.highlight

  # The SuperFences extension allows for arbitrary nesting of code and content blocks inside each other,
  # including admonitions, tabs, lists and all other elements.
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/?h=superfence#superfences
  - pymdownx.superfences

  # The Admonition extension adds support for admonitions,
  # more commonly known as call-outs, which can be defined in Markdown by using a simple syntax.
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#admonition
  - admonition

  # The Attribute Lists extension allows us to add HTML attributes and CSS classes to almost every Markdown inline- and block-level element with a special syntax.
  # We're using this to get a button on the homepage that links to our GitHub app.
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#attribute-lists
  - attr_list

  # This configuration adds the ability to align images, add captions to images (rendering them as figures), and mark large images for lazy-loading.
  # We also need the attr_list markdown extension, which is enabled in the lines above this comment.
  # https://squidfunk.github.io/mkdocs-material/reference/images/#configuration
  - md_in_html

  # We need this to get emojis working on Material for MkDocs.
  # We also need the attr_list extension, which is already enabled in the lines above this comment.
  # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#configuration
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # The Details extension supercharges the Admonition extension, making the resulting call-outs collapsible, allowing them to be opened and closed by the user.
  # We're using this to enable collapsible admonition blocks for the list of bug reports and feature requests per manager.
  - pymdownx.details

  # The Abbreviations extension adds the ability to add a small tooltip to an element, by wrapping it with an abbr tag.
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#abbreviations
  - abbr

  # The Snippets extension adds the ability to embed content from arbitrary files into a document, including other documents or source files, by using a simple syntax.
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#snippets
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

  # The Footnotes extension adds the ability to add footnotes.
  # https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - footnotes

# Plugins
plugins:
  - search

# Page Tree/Sidebar
# https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
nav:
  - Home: 'index.md'
  - Getting Started:
      - 'Use Cases': 'getting-started/use-cases.md'
      - 'Running Renovate': 'getting-started/running.md'
      - 'Self-Hosting Examples': 'examples/self-hosting.md'
      - 'Installing & Onboarding': 'getting-started/installing-onboarding.md'
      - 'Private Packages': 'getting-started/private-packages.md'
  - Troubleshooting: 'troubleshooting.md'
  - Configuration:
      - 'Self-hosted': 'self-hosted-configuration.md'
      - 'Repository': 'configuration-options.md'
      - 'Presets': 'config-presets.md'
  - Key Concepts:
      - 'Presets': 'key-concepts/presets.md'
      - 'Dependency Dashboard': 'key-concepts/dashboard.md'
      - 'Pull Requests': 'key-concepts/pull-requests.md'
      - 'Renovate Scheduling': 'key-concepts/scheduling.md'
      - 'Automerge': 'key-concepts/automerge.md'
  - Renovate Modules:
      - 'Platforms': 'modules/platform.md'
      - 'Managers': 'modules/manager.md'
      - 'Datasources': 'modules/datasource.md'
      - 'Versioning': 'modules/versioning.md'
  - Language Support:
      - 'Bazel': 'bazel.md'
      - 'Docker': 'docker.md'
      - 'Golang': 'golang.md'
      - 'Java': 'java.md'
      - 'JavaScript': 'javascript.md'
      - 'Node.js Versions': 'node.md'
      - 'Nuget': 'nuget.md'
      - 'PHP': 'php.md'
      - 'Python': 'python.md'
      - 'Ruby': 'ruby.md'
  - Deep Dives:
      - 'Should you Pin your Javascript Dependencies?': 'dependency-pinning.md'
      - 'Config Template Editing': 'configuration-templates.md'
      - 'Updating and Rebasing Branches': 'updating-rebasing.md'
      - 'Semantic Commit Messages': 'semantic-commits.md'
      - 'Noise Reduction': 'noise-reduction.md'
  - Included Presets:
      - 'Compatibility Presets': 'presets-compatibility.md'
      - 'Default Presets': 'presets-default.md'
      - 'Docker Presets': 'presets-docker.md'
      - 'Full Config Presets': 'presets-config.md'
      - 'Group Presets': 'presets-group.md'
      - 'Helper Presets': 'presets-helpers.md'
      - 'Monorepo Presets': 'presets-monorepo.md'
      - 'npm Presets': 'presets-npm.md'
      - 'Package Presets': 'presets-packages.md'
      - 'Preview Presets': 'presets-preview.md'
      - 'Regex Manager Presets': 'presets-regexManagers.md'
      - 'Replacement Presets': 'presets-replacements.md'
      - 'Schedule Presets': 'presets-schedule.md'
      - 'Workaround Presets': 'presets-workarounds.md'
  - All Other:
      - User Stories:
          - 'Swissquote': 'user-stories/swissquote.md'
      - 'Security and Permissions': 'security-and-permissions.md'
      - 'Merge Confidence': 'merge-confidence.md'
      - 'Templates': 'templates.md'
      - 'Frequently Asked Questions': 'faq.md'
      - 'Known Limitations': 'known-limitations.md'
      - 'Release notes for major versions': 'release-notes-for-major-versions.md'
  - About Us: 'about-us.md'
